### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by steveoh** [agolaszewski/Inquirer.cs#57]
I'm trying to use this project in a .net 4.5 or 4.6 or 4.6.1 project but am having trouble. I don't see 4.6.2 as an option for my project type. My VS2017 is up to date and windows is up to date. Do you know what's up?

`The primary reference "InquirerCS, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.6.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.1".`

**Comment by steveoh** [comment]
installing the 4.6.2 developer pack fixed that but is there a way with nuget packages to avoid this issues?

https://blogs.msdn.microsoft.com/benjaminperkins/2017/03/23/net-framwork-4-6-2-not-in-visual-studio-2017/

**Comment by agolaszewski** [comment]
Hey. From now on  nuget package works from 4.5 up
